spring:
  datasource:
    url: jdbc:h2:file:~/cuberboot-db
    driver-class-name: org.h2.Driver
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.hbm2ddl.import_files: bootstrapDB/boot.sql
  thymeleaf:
    mode: HTML5
    reactive:
      full-mode-view-names: classpath:/templates/**/*.html
server:
  port: 1212